[package]
name = "dnd"
version = "0.1.0"
authors = ["Evgeny Varganov <gokjer@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
